# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: 502B
author: ...
logo: logo.svg

execute:
  execute_notebooks: auto
  allow_errors: true

latex:
  latex_documents:
    targetname: book.tex

bibtex_bibfiles:
  - references.bib

repository:
  url: https://github.com/younesStrittmatter/502B # Online location of your book
  path_to_book: book  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

html:
  use_repository_button: true
  baseurl: https://younesstrittmatter.github.io/502B/

launch_buttons:
  colab_url: https://colab.research.google.com
  thebe: false


sphinx:
  config:
    html_extra_path: ['assets']

# Jinja2 variables
parse:
  myst_substitutions:
    repo_url: "https://github.com/younesStrittmatter/502B"
    base_url: "https://younesstrittmatter.github.io/502B"
    assets_url: "https://younesstrittmatter.github.io/502B/assets/"